[versions]
kotest = "6.1.3"
kotshi = "4.0.0"

[libraries]
http4k-bom = "org.http4k:http4k-bom:6.27.0.0"
kotlin-logging = "io.github.oshai:kotlin-logging-jvm:7.0.14"
kotshi-api = { module = "se.ansman.kotshi:api", version.ref = "kotshi" }
kotshi-compiler = { module = "se.ansman.kotshi:compiler", version.ref = "kotshi" }
rtfparserkit = "com.github.joniles:rtfparserkit:1.16.0"
slf4j-bom = "org.slf4j:slf4j-bom:2.0.17"
crac = "org.crac:crac:1.5.0"

kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
mockk = "io.mockk:mockk:1.14.9"

[plugins]
decycle = { id = "de.obqo.decycle", version = "1.2.5" }
dependency-check = { id = "org.owasp.dependencycheck", version = "12.2.0" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.6" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.5" }
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }
test-logger = { id = "com.adarshr.test-logger", version = "4.0.0" }
